<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Yogi-PC" name="Difffernt testing feature Test" tests="23" failures="2" timestamp="7 Nov 2020 06:58:37 GMT" time="82.11" errors="0">
  <testcase name="googleTitleTest" time="0.043" classname="TestNG_Concepts.AssertionConcept"/>
  <testcase name="infinitLooP" time="2.03" classname="TestNG_Concepts.ExceptionTimeOut">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNG_Concepts.ExceptionTimeOut.infinitLooP() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNG_Concepts.ExceptionTimeOut.infinitLooP() didn't finish within the time-out 2000
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at java.io.PrintStream.write(Unknown Source)
	at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
	at sun.nio.cs.StreamEncoder.flushBuffer(Unknown Source)
	at java.io.OutputStreamWriter.flushBuffer(Unknown Source)
	at java.io.PrintStream.newLine(Unknown Source)
	at java.io.PrintStream.println(Unknown Source)
	at TestNG_Concepts.ExceptionTimeOut.infinitLooP(ExceptionTimeOut.java:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- infinitLooP -->
  <testcase name="sum" time="0.003" classname="TestNG_Concepts.invocationCount"/>
  <testcase name="sum" time="0.04" classname="TestNG_Concepts.invocationCount"/>
  <testcase name="sum" time="0.009" classname="TestNG_Concepts.invocationCount"/>
  <testcase name="sum" time="0.013" classname="TestNG_Concepts.invocationCount"/>
  <testcase name="sum" time="0.072" classname="TestNG_Concepts.invocationCount"/>
  <testcase name="sum" time="0.01" classname="TestNG_Concepts.invocationCount"/>
  <testcase name="sum" time="0.006" classname="TestNG_Concepts.invocationCount"/>
  <testcase name="sum" time="0.015" classname="TestNG_Concepts.invocationCount"/>
  <testcase name="sum" time="0.014" classname="TestNG_Concepts.invocationCount"/>
  <testcase name="sum" time="0.009" classname="TestNG_Concepts.invocationCount"/>
  <testcase name="LoginPage" time="0.004" classname="TestNG_Concepts.dependsOnMehode">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
	at TestNG_Concepts.dependsOnMehode.LoginPage(dependsOnMehode.java:10)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- LoginPage -->
  <testcase name="Homepage" time="0.0" classname="TestNG_Concepts.dependsOnMehode">
    <skipped/>
  </testcase> <!-- Homepage -->
  <testcase name="Test1" time="0.024" classname="TestNG_Concepts.Grouping_concept"/>
  <testcase name="GoogleTitle" time="0.019" classname="TestNG_Concepts.TestNG_basics"/>
  <testcase name="Test2" time="0.008" classname="TestNG_Concepts.Grouping_concept"/>
  <testcase name="GooglelogoTest" time="0.457" classname="TestNG_Concepts.TestNG_basics"/>
  <testcase name="Test3" time="0.002" classname="TestNG_Concepts.Grouping_concept"/>
  <testcase name="Test1" time="0.002" classname="TestNG_Concepts.TestNG_basics"/>
  <testcase name="Test4" time="0.002" classname="TestNG_Concepts.Grouping_concept"/>
  <testcase name="Test2" time="0.004" classname="TestNG_Concepts.TestNG_basics"/>
  <testcase name="Test5" time="0.005" classname="TestNG_Concepts.Grouping_concept"/>
</testsuite> <!-- Difffernt testing feature Test -->
